language: node_js
jdk:
  - oraclejdk8
node_js:
  - 10

os:
  - linux

dist: trusty

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)


jobs:
  include:
    - script:
      - sbt bsp4j/xtend test bsp4j/test
      - test -z $(git ls-files --modified)
    - stage: release
      script: sbt docs/docusaurusPublishGhpages

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
  yarn: true

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

before_install:
  - git fetch --tags
